### ISSUE TITLE
Solidity syntax highlighting

### ISSUE THREAD

**Issue by JustinDrake** [dankrad/rsa-bounty#3]
To add syntax highlighting (e.g. for Github) add a `.gitattributes` file with `*.sol linguist-language=Solidity`. (See [this article](https://medium.com/@danielque/psa-how-to-fix-githubs-syntax-highlighting-for-solidity-4e9867c540b6).)

**Comment by dankrad** [comment]
Fixed in 012eda8234394d46aa1e833882ee997ff3b4aa72
